Repository stolostron/search-v2-operator-bundle, pull requests merged in 2022-09, with the labels that each got.

#4 Updated component version
  COMPONENT_VERSION
  Makefile
  Makefile.prow
  scripts/bundle-image-pickup.sh
Labels: lgtm, approved, dco-signoff: yes

#5 updated build for 9/1/22
  README.md
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: do-not-merge/hold, lgtm, approved, dco-signoff: yes

#6 Update images to latest
  README.md
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes

#7 Update images to latest
  README.md
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#8 Update postgres and search images
  .gitignore
  Makefile
  README.md
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#9 Updated bundle image to latest tags and updated doc flow
  .gitignore
  CHANGELOG.md
  README.md
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
  docs/images/bundle-image-pickup-manual.gif
  docs/images/bundle-image-pickup-silent.gif
  pg-snapshot.ver
  scripts/bundle-image-pickup.sh
  scripts/log-colors.sh
  snapshot.ver
Labels: lgtm, approved, dco-signoff: yes

#10 Update images (9-20-22)
  CHANGELOG.md
  bundle/manifests/search-v2-operator.clusterserviceversion.yaml
Labels: lgtm, approved, dco-signoff: yes

#2 Added schedule workflow for bundle image update
  .github/workflows/bundle-image-update.yml
Labels: lgtm, approved, dco-signoff: yes
